Repository SU-SWS/decanter-react, pull requests merged in 2021-09, with the labels that each got.

#61 Update GlobalFooter.js
  src/GlobalFooter/GlobalFooter.js
Labels: size/xs

#56 ADAPT-2102: Hero component
  src/Hero/Hero.js
  src/Hero/Hero.levers.js
  src/Hero/Hero.stories.js
  src/Hero/Hero.test.js
Labels: size/s

#65 ADAPT-3096: Text Field
  .storybook/stories/FormElements.stories.js
  package-lock.json
  src/InlineError/InlineError.js
  src/InlineError/InlineError.stories.js
  src/InlineError/InlineError.test.js
  src/InlineValid/InlineValid.js
  src/InlineValid/InlineValid.stories.js
  src/InlineValid/InlineValid.test.js
  src/Label/Label.js
  src/Label/Label.levers.js
  src/Label/Label.stories.js
  src/Label/Label.test.js
  src/TextField/TextField.js
  src/TextField/TextField.stories.js
  src/TextField/TextField.test.js
  src/index.js
Labels: size/l

#70 ADAPT-3128: Error Summary Box (and List) variation
  src/Alert/Alert.js
  src/Alert/Alert.levers.js
  src/Alert/Alert.stories.js
  src/DismissButton/DismissButton.js
  src/DismissButton/DismissButton.levers.js
Labels: size/s

#75 ADAPT-3123: Add info button variant
  src/Button/Button.stories.js
  src/HeroIcon/HeroIcon.js
  src/HeroIcon/HeroIcon.stories.js
  src/common/icon/getIconClasses.js
  src/common/icon/icon.levers.js
Labels: size/xs

#71 Adapt 3717: Hero Icon updates
  .nvmrc
  dist/decanter-react.js
  dist/decanter-react.modern.js
  dist/decanter-react.module.js
  dist/decanter-react.umd.js
  package-lock.json
  package.json
  src/Alert/Alert.js
  src/Button/Button.js
  src/Button/Button.stories.js
  src/CtaButton/CtaButton.js
  src/CtaLink/CtaLink.js
  src/DismissButton/DismissButton.js
  src/HeroIcon/HeroIcon.js
  src/HeroIcon/HeroIcon.stories.js
  src/HeroIcon/HeroIcon.test.js
  src/InlineError/InlineError.js
  src/InlineValid/InlineValid.js
  src/LocalFooter/LocalFooter.js
  src/common/icon/getIconClasses.js
  src/common/icon/icon.levers.js
  src/index.js
Labels: minor, size/xl
