Repository SU-SWS/decanter-react, pull requests merged in 2021-06, with the labels that each got.

#47 ADAPT-1776 Card possible tweaks
  postcss.config.js
  src/Card/Card.Content.js
  src/Card/Card.Headline.js
  src/Card/Card.Image.js
  src/Card/Card.Superhead.js
  src/Card/Card.js
  src/Card/Card.levers.js
  src/Card/Card.stories.js
  src/CtaLink/CtaLink.js
  src/Heading/Heading.js
Labels: size/l

#33 ADAPT-1776 Build Card Component
  .codeclimate.yml
  .github/workflows/eslint.yml
  dist/decanter-react.js
  dist/decanter-react.modern.js
  dist/decanter-react.module.js
  dist/decanter-react.umd.js
  package-lock.json
  package.json
  postcss.config.js
  src/Alert/Alert.stories.js
  src/Card/Card.Content.js
  src/Card/Card.Headline.js
  src/Card/Card.Image.js
  src/Card/Card.Superhead.js
  src/Card/Card.js
  src/Card/Card.levers.js
  src/Card/Card.stories.js
  src/Card/Card.test.js
  src/CtaLink/CtaLink.js
  src/GlobalFooter/GlobalFooter.stories.js
  src/Heading/Heading.js
  src/IdentityBar/IdentityBar.stories.js
  src/Lockup/Lockup.stories.js
  src/index.js
Labels: alpha, size/xl

#46 ADAPT-000: React 17 Support
  package.json
Labels: patch, size/xs

#50 ADAPT-2695 Create Poster component
  dist/decanter-react.js
  dist/decanter-react.modern.js
  dist/decanter-react.module.js
  dist/decanter-react.umd.js
  package-lock.json
  src/Poster/Poster.Content.js
  src/Poster/Poster.Headline.js
  src/Poster/Poster.Image.js
  src/Poster/Poster.js
  src/Poster/Poster.levers.js
  src/Poster/Poster.stories.js
  src/Poster/Poster.test.js
  src/index.js
Labels: patch, size/xl

#53 ADAPT-000: Poster release fixup.
  .babelrc
  dist/decanter-react.js
  dist/decanter-react.modern.js
  dist/decanter-react.module.js
  dist/decanter-react.umd.js
  package-lock.json
  package.json
Labels: patch, size/l

#52 ADAPT-000: Remove div and setdanger in alert component story.
  .eslintrc
  src/Alert/Alert.js
  src/Alert/Alert.stories.js
Labels: size/xs

#54 ADAPT-000: NPM Package Version Updates
  .babelrc
  package-lock.json
  package.json
  src/Button/Button.test.js
  src/Card/Card.test.js
  src/Container/Container.test.js
  src/CtaButton/CtaButton.test.js
  src/CtaLink/CtaLink.test.js
  src/DismissButton/DismissButton.test.js
  src/Heading/Heading.test.js
  src/Logo/Logo.test.js
  src/Poster/Poster.test.js
  src/Skiplink/Skiplink.test.js
  src/SrOnlyText/SrOnlyText.test.js
Labels: alpha, size/xl
