Repository SU-SWS/decanter-react, pull requests merged in 2021-05, with the labels that each got.

#34 ADAPT-2517: Added autorelease github action.
  .github/workflows/autorelease.yml
  package-lock.json
  package.json
Labels: patch

#35 ADAPT-2157: Fix for autorelease action.
  .github/workflows/autorelease.yml
Labels: patch

#37 ADAPT-2517: Debugging (Switch decanter package to use semantic versioning)
  package-lock.json
  package.json
Labels: patch

#38 ADAPT-000: Update packages.
  package-lock.json
Labels: patch

#39 ADAPT-000: Update packages... again.
  package-lock.json
Labels: patch

#40 Update CHANGELOG.md
  CHANGELOG.md
Labels: patch

#41 1.0.2
  CHANGELOG.md
Labels: patch

#42 1.0.2
  package.json
Labels: patch

#43 Create label.yml
  .github/auto-label.json
  .github/workflows/label.yml
Labels: size/xs

#44 ADAPT-2517: Follow-up tweaks for auto-release action.
  .github/workflows/autorelease.yml
  .npmrc
  package-lock.json
  package.json
Labels: alpha, size/xl

#45 ADAPT-000: Update README.md
  README.md
Labels: patch, size/xs
